### ISSUE TITLE
sqlite3 database not supported

### ISSUE THREAD

**Issue by geboro** [combogenomics/DuctApe#11]
Hello.

I am trying DuctApe with the tutorial dataset (smeliloti), and I couldn't pass the first step, since `dape init` failed to create the sqlite3 database

I'm using a xubuntu 22.04.4 LTS OS running on a Xeon Gold 6140 system, and I followed the installation instructions with conda (mamba) as per the tutorial.

Thanks!

```
$ dape init -n smeliloti
10:22:52 - Could not create the database!
10:22:52 - database is locked
10:22:52 - You can remove or rename the old project file
Traceback (most recent call last):
  File "/home/bioinf/miniforge3/envs/ductape/bin/dape", line 1015, in <module>
    touchProject(project)
  File "/home/bioinf/miniforge3/envs/ductape/lib/python3.12/site-packages/ductape/actions.py", line 4832, in touchProject
    proj = Project(project)
           ^^^^^^^^^^^^^^^^
  File "/home/bioinf/miniforge3/envs/ductape/lib/python3.12/site-packages/ductape/storage/SQLite/database.py", line 126, in __init__
    self.getProject()
  File "/home/bioinf/miniforge3/envs/ductape/lib/python3.12/site-packages/ductape/storage/SQLite/database.py", line 154, in getProject
    cursor = conn.execute('select * from project limit 1;')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: project
```

**Comment by mgalardini** [comment]
Hi, I'm afraid DuctApe is not maintained much anymore. I might find some time to look at this but I cannot really make any commitment, sorry
