### ISSUE TITLE
dgenome start - Bio-alphabet? dphenome add - No biolog data was found!

### ISSUE THREAD

**Issue by ESykes124** [combogenomics/DuctApe#8]
Hi Marco,

Thanks so much for making a really great package. I am going though the specified commands using the example Acinetobacter data provided in the supplemental data 3 from https://doi.org/10.1016/j.ygeno.2013.11.005. I was able to set up the project and add the genomic data and KASS outputs. Then when I go to begin the pangenome estimation / KEGG mapping step, I run into the following error:
**I am running dape 0.18.2**

(ductape) kumarlab@kumarlab:~/Documents/Ellen/Biolog$ dgenome start -n 4 -p Acin_
usage: dgenome [-h] [-p project] [-w workdir] [-v] [--version]
               {init,add,add-dir,add-ko,add-orth,start,annotate,deannotate,stats,export,rm,clear} ...
dgenome: error: unrecognized arguments: -p Acin_
(ductape) kumarlab@kumarlab:~/Documents/Ellen/Biolog$ dgenome start -n 4
21:24:22 - 4 organisms are present
Traceback (most recent call last):
  File "/home/kumarlab/anaconda3/envs/ductape/lib/python3.11/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kumarlab/anaconda3/envs/ductape/bin/dgenome", line 477, in <module>
    ret = options.func(options, wdir, project)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kumarlab/anaconda3/envs/ductape/bin/dgenome", line 101, in dstart
    SeqIO.write(gen.getRecords(organism.org_id),
  File "/home/kumarlab/anaconda3/envs/ductape/lib/python3.11/site-packages/Bio/SeqIO/__init__.py", line 517, in write
    for record in sequences:
  File "/home/kumarlab/anaconda3/envs/ductape/lib/python3.11/site-packages/ductape/storage/SQLite/database.py", line 708, in getRecords
    from Bio import Alphabet
  File "/home/kumarlab/anaconda3/envs/ductape/lib/python3.11/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
#######################################################################

I then tried to use a different module of DuctApe and simply do some phenome analysis with the same data. I ran into the following error:

(ductape) kumarlab@kumarlab:~/Documents/Ellen/Biolog$ dphenome add 19606.csv 19606
21:31:33 - YAML/OPM parsing failed!
21:31:33 - CSV (new version) parsing failed!
21:31:33 - CSV (old version) parsing failed!
21:31:33 - No biolog data was found!

I must be missing something because these files should be in the exact format for analysis so I am not sure what is wrong. Any help would be appreciated!

Thanks so much,

Ellen

**Comment by mgalardini** [comment]
This is likely due to biopython changing its behavior recently. Regarding the second error I would need to check.

This software is not maintained anymore and so it might take me some time...

**Comment by AbhiGene** [comment]
Fixed this by simply downgrading Biopython versions with `pip install biopython==1.68`
